# Generated by Django 4.2.18 on 2026-09-02 13:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldocument',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='D:\\PYTHON\\API\\Safarnama\\media'), upload_to='travel_documents/'),
        ),
    ]
