# Generated by Django 4.2.18 on 2026-09-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_traveldocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='file_data',
            field=models.BinaryField(blank=True, help_text='In-database binary storage for serverless Vercel and free PDF viewing', null=True),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='mime_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='travel_documents/'),
        ),
    ]
