# Generated by Django 4.2.18 on 2026-09-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_traveldocument_file_data_traveldocument_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='Cloudinary CDN URL for image assets', max_length=500, null=True),
        ),
    ]
